### ISSUE TITLE
support using request.tm as the transaction manager if available

### ISSUE THREAD

**Issue by mmerickel** [Pylons/pyramid_mailer#76]
pyramid_tm exposes `request.tm` which may not use the threadlocal manager. We should support detecting this and forwarding it to `QueuedMailDelivery` and `DirectMailDelivery` which both support the `transaction_manager=` argument.

**Comment by miohtama** [comment]
I ran this issue with Celery tasks. Outbound email was never send, because one cannot reliably use `transaction.manager` under Celery tasks, but one needs to use `request.tm` (or any other explicitly passed tm).

See https://github.com/websauna/websauna/issues/85
