### ISSUE TITLE
Testing mailer broken if pyramid_tm is in use

### ISSUE THREAD

**Issue by dairiki** [Pylons/pyramid_mailer#82]
Version 0.15 introduces a new `Mailer.bind()` method, which is used by `get_mailer()` to implement support for request-local transactions.  This method is not implemented, however, on `DummyMailer` (and `DebugMailer`), so when the testing mailer is in use (alongside `pyramid_tm`,) `get_mailer()` fails with:
```
pyramid_mailer/__init__.py:44: AttributeError: 'DummyMailer' object has no attribute 'bind'
```

Possible solutions include
- Implement `.bind()` on `DummyMailer` and `DebugMailer`
- Have `get_mailer()` check for the existence of the `.bind` method before calling it

**Comment by tseaver** [comment]
@dairiki Thanks for the report!  I think the first suggested approach makes more sense.

**Comment by mmerickel** [comment]
At the very least we should implement `bind` on the dummy/debug mailers. However related to #79 we also need to add the request method in the case of `config.include('pyramid_mailer.testing')`.
